services:
  - type: web
    name: topsis-web-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 120 --workers 1 --threads 2 app:app"
    env:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false